### ISSUE TITLE
1.0.0 TODO

### ISSUE THREAD

**Issue by ChronoVortex** [ChronoVortex/FTL-Multiverse-Fusion#1]
- [ ] Add @arcburnergit's addon icon system
  - [ ] Needs to be reworked to use the button system implemented in HS 1.9.0
  - [ ] Fix buttons appearing in credits screen, being clickable while in the ESC menu and tint in ESC menu
  - [ ] Add scroll buttons on left and right to remove addon icon limit
- [ ] Save position of augment value displays in metavars
- [ ] Fix enemy augment display remaining after enemy is destroyed
- [ ] Make enemy drone and missile count display toggleable from the addon button event, move to enemy box render event
- [ ] Add @Choosechee's instant clone and heal, make togglable from the addon button event
- [ ] New sprite for Fusion addon icon to replace Inferno-Core's icon
